version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout

      - run:
          name: Build and Test
          command: |
            ./mvnw clean package

      - run:
          name: Deploy
          command: |
            # Add your deployment commands here

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
